# Generated by Django 3.2.3 on 2021-06-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passanger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passanger',
            new_name='Passenger',
        ),
    ]
