# Generated by Django 3.2.5 on 2021-08-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nifty', '0002_assignment_course_file_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='completed_by',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='submitted_by',
            new_name='submitted',
        ),
    ]
