# Generated by Django 3.2.5 on 2021-08-10 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nifty', '0003_auto_20210807_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nifty.assignment'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='lecture',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
