# Generated by Django 3.2.5 on 2021-08-10 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nifty', '0004_auto_20210810_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='completed',
            field=models.ManyToManyField(blank=True, null=True, related_name='completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='form',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='submitted',
            field=models.ManyToManyField(blank=True, null=True, related_name='submitted', to=settings.AUTH_USER_MODEL),
        ),
    ]
