# Generated by Django 3.2.5 on 2021-08-15 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nifty', '0005_auto_20210810_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='completed',
            field=models.ManyToManyField(blank=True, related_name='completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='submitted',
            field=models.ManyToManyField(blank=True, related_name='submitted', to=settings.AUTH_USER_MODEL),
        ),
    ]
