# Generated by Django 3.2.5 on 2021-08-20 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nifty', '0006_auto_20210815_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nifty.course')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='certificates',
            field=models.ManyToManyField(blank=True, related_name='certificates', to='nifty.Certificate'),
        ),
    ]
